package com.course.java.model;

public enum City {
    AMSTERDAM, ATHENS, BERN, BRUSSELS, BELGRADE, BUCHAREST, DUBLIN, HELSINKI, BRATISLAVA, LUBLANA, WARSAW, CRACOW,
    MADRID, PARIS, OSLO, STOCKHOLM, VIENNA, COPENHAGEN, PRAGA, BUDAPEST, LONDON, NYC, CHICAGO, DALLAS, MIAMI,
    LOS_ANGELES, SAN_DIEGO, SAN_FRANCISCO, LAS_VEGAS, WASHINGTON_DC, BOSTON, DETROIT, INDIANAPOLIS, ATLANTA;
}
